= JavaFX fxml Files

The examples in this project demonstrate several different ways to use fxml files.

== Example 1

First Simple example. Note that `greet1.fxml` also defines the controller (can be entered in bottom left area of SceneBuilder window):

[source,xml]
.greet1.fxml
----
<Pane ... fx:controller="org.svenehrke.javafxdemos.fxmlstages.fxml01.GreetController">
   <children>
      ...
   </children>
</Pane>
----

_Main1.java_ loads it as follows:

[source,java]
.Main1.java
----
Pane pane = FXMLLoader.load(Main1.class.getResource("/greet1.fxml"));
----

== Example 2

This example makes use of `FXMLLoader.setControllerFactory(...)`:

[source,java]
.Main2.java
----
FXMLLoader loader = new FXMLLoader(Main2.class.getResource("/greet2.fxml"));
loader.setControllerFactory((Class<?> c) -> new GreetController2());
----

By default JavaFX instantiates the controller based upon the classname defined in the fxml file (see _Main1.java_).
Using `setControllerFactory` the passed in callback is in charge to create an instance of the controller. This way the application
has full control over how the controller is instantiated and even which controller is instantiated. This means you can for example apply
dependency injection to the controller before it is handed back to JavaFX.

At first I thought that when I use `setControllerFactory` I can omit the `fx:controller` attribute in my _fxml_ file. I thought it would not make to specify it in the fxml
since the routine determines which object is used. Having it in both places is contradictory. But it turns out that you have to do it anyway. Otherwise
the function won't be called. So this feels a bit strange. The good news is: as long as the class you specify in `fx:controller` exists everything is OK. You
can even use `java.lang.String` as value if you want. All that happens is that the specified class is passed
as input to your controller factory.

Note that when your controller factory returns null it means that the default controller construction mechanism will be employed by the loader. If
you have used `java.lang.String` as controller class the GUI will start anyway and will silently ignore the fact that it cannot use _String_ as a controller class.

== Example 3

This example makes use of the things we learned in Example 2. It will not only create and return a controller using `FXMLLoader.setControllerFactory(...)`.
In addition it will initilize the newly instantiated controller with certain values before it returns it to JavaFX. Therefore `GreetController3` has a
new attribute `String prefix` so that the greeting _Hello_ which was hard coded so far can be configured. In our simple example this is done as follows:

[source,java]
.Main3.java
----
loader.setControllerFactory((Class<?> c) -> {
  GreetController3 controller = new GreetController3();
  controller.prefix = "Good morning"; // dependency injection simulation for demonstration purposes
  return controller;
});
----

So first the controller is created, then its prefix is set to _Good morning_ and only then it is returned back to JavaFX.

So now it becomes clear that at this point we could use a general dependency injection mechanism for the controller. And this is exactly what
Adam Bien's mini framework http://afterburner.adam-bien.com/[afterburner.fx] is for.

You can find a variant of this Greeting Application using afterburner.fx here: https://github.com/svene/javafx_demos/tree/master/fxml_stages/fxml_02

== Think about it

It is very easy to end up with the situation in Example 3. When a new GUI is created from scratch it all starts with the fact that we want to
see something happen quickly, for example when we click a button:
[source,java]
.Step 1
----
greetingButton.setOnAction(event -> System.out.println("button pressed");
----

We are happy because it is working. But printing static text is not really the goal. So the next step is to take the TextField into account:

[source,java]
----
greetingButton.setOnAction(event -> System.out.println("Hello " + nameTextField.getText());
----

Great it is working! But printing to the console is not what we want so let us add a label which displays the text:

[source,java]
----
greetingButton.setOnAction(event -> greetingLabel.setText("Hello " + nameTextField.getText());
----

And then it would be great if we could somehow pass in the greeting prefix ("Hello") from outside so that it can easily be changed to "Good morning" for example:

[source,java]
----
greetingButton.setOnAction(event -> greetingLabel.setText(
  String.format("GreetController2: %s %s", prefix, nameTextField.getText()))
);
----

This means the view needs to provide a means that client code can pass in the prefix.
The more complex the view becomes the more information needs to be passed into the view. This can be somehow alleviated by passing in a model holding the information the view needs. Using DI can even
eliminate this. But then there is still the behavior (the code handling a button click for example) mixed into the view and it all becomes very complex and messy. This also leads to an increasing number
of dependencies from the view to other parts of our application. So in summary the most important disadvantages of this approach are:

* Initialization of the view and dependency injection of the right things at the right time can become difficult
* With an increasing number of widgets the the view becomes more and more dependent upon non GUI related things
* The coupling between view and behaviour becomes very entangled

Although it works and some of the issues might be a matter of taste in my opinion the approach starting with step 1 is a huge seductive trap and many applications fall into it because
it seems to be the obvious way to take.

Personally I prefer and recommend the following alternative approach: keep the view to an absolute minimum in the sense of a http://martinfowler.com/eaaDev/PassiveScreen.html[_Passive View_].
The next section demonstrates how this is done with our example.

== Example 4

A _Passive View_ version kept to the absolute minimum for our example looks as follows:

[source,java]
.GreetView4.java
----
public class GreetView4 {

  @FXML
  Button greetingButton;

  @FXML
  TextField nameTextField;

  @FXML
  Label greetingLabel;
}
----

To bind behavior and state to the view a so called _ViewBinder_ is used:

[source,java]
.ViewBinder4.java
----
public class ViewBinder4 {
  public void bind(GreetView4 view, Context4 context) {
    view.nameTextField.textProperty().bindBidirectional(context.name);
    view.greetingLabel.textProperty().bind(context.greeting);
    view.greetingButton.setOnAction(event -> {
      context.greeting.setValue(String.format("%s %s", context.prefix.getValue(), context.name.getValue()));
    } );
  }
}
----

Initialization is easy:
[source,java]
.Main4.java
----
...
  @Override
  public void start(Stage primaryStage) throws Exception {
    Context4 context = new Context4();
    context.prefix.setValue("Good morning");
    context.name.setValue("Duke");

    FXMLLoader loader = new FXMLLoader(Main4.class.getResource("/greet4.fxml"));
    Pane pane = loader.load();
    GreetView4 view = loader.getController();

    new ViewBinder4().bind(view, context);

    Scene scene = new Scene(pane);
    primaryStage.setScene(scene);
    primaryStage.setTitle("Greet 4 FXML");
    primaryStage.show();
...
----

Taking this approach the disadvantages with the previous approach are gone. Also notice that we do not need a _ControllerFactory_ and no injection into the view anymore. Note that this approach is
not restricted to cases where you use fxml. For me it makes perfect sense for programmatically built views as well.


=== Terms
The _View_ (Greetview4) is the JavaFX Scenebuilder Controller. Since it does not control anything anymore _View_ makes more sense to me.
_ViewBinder_ corresponds to _Controller_ in the _Passive View_ pattern but since it binds state and behavior to widgets and does not control anything itself _ViewBinder_ sounds better to me.

